driverClassName = com.mysql.jdbc.Driver
url = jdbc:mysql://192.168.174.100:3306/xd_web?useUnicode=true&characterEncoding=utf-8&useSSL=false&connectTimeout=3000&socketTimeout=10000
username = root
password = root
initialSize=2
maxActive=30
maxIdle=10
minIdle=2
maxWait=5000
testOnBorrow=true
validationQuery=SELECT 1
